### ISSUE TITLE
Use separate Redis deployment

### ISSUE THREAD

**Issue by LarsAC** [openanalytics/shinyproxy-operator#44]
Hello,

I tried to use a separate deployment of Redis / Sentinel that was created using Bitnami's helm chart. I can exec into one of the redis pods, run `redis-cli` and `AUTH <my-passwd>` or `AUTH default <my-passwd>` successfully.

However, I keep getting authentication errors from the Shinyproxy pod that was created from the operator:

```
Caused by: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://************@redis-node-0.redis-headless.redis:26379, redis://************@redis-node-1.redis-headless.redis:26379, redis://************@redis-node-2.redis-headless.redis:26379]
```
and further down in the log
```
Caused by: io.lettuce.core.RedisCommandExecutionException: WRONGPASS invalid username-password pair or user is disabled.
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        ... 22 common frames omitted
```

This looks like there is actually an exception received from Redis so that the connection seems to work - is that assumption correct ?

What needs to be done to make the Shinyproxy work with a separate Redis ?

Lars

**Comment by LEDfan** [comment]
Hi

In principle, nothing special is needed to make ShinyProxy work with the external redis server. The Redis deployment inside this repository is also based on the bitnami helm chart (https://github.com/openanalytics/shinyproxy-operator/blob/master/docs/deployment/bases/redis-sentinel/chart-src/kustomization.yml)

I can reproduce the error you have when providing an incorrect password for the sentinel config. Can you double check this? Can you maybe post your shinyproxy config?
